EXTCONF:
    realurl:
        _DOMAINS:
            encode:
            - { GETvar: L, value: '0', useConfiguration: _DEFAULT }
            - { GETvar: L, value: '1', useConfiguration: _DEFAULT }
            - { GETvar: L, value: '2', useConfiguration: _DEFAULT }

        default.tld:
            init:
                enableCHashCache: true
                appendMissingSlash: 'ifNotFile'
                adminJumpToBackend: true
                enableUrlDecodeCache: true
                enableUrlEncodeCache: true
                emptyUrlReturnValue: /
                disableErrorLog: true
                postVarSet_failureMode: 'redirect_goodUpperDir'
            pagePath:
                rootpage_id: '1'
                type: user
                userFunc: 'Tx\Realurl\UriGeneratorAndResolver->main'
                spaceCharacter: '-'
                languageGetVar: 'L'
                expireDays: 3
                dontResolveShortcuts: false
            fileName:
                defaultToHTMLsuffixOnPrev: false

        '%conf(EXTCONF.tp3_site.defaultLanguageDomain)%': '_DEFAULT'
        '%conf(EXTCONF.tp3_site.englishDomain)%': '_DEFAULT'
