BE:
    installToolPassword: $pbkdf2-sha256$25000$y.I4SGEeOzQAiW7cp78Ncg$1qnX0R2eeRRwge444q0QccdU415u530o7WxiPxQmFOI
DB:
    Connections:
        Default:
            dbname: c1typo3
            driver: mysqli
            host: 2.2.2.50
            password: zs1yOCf@U
            port: 3306
            unix_socket: /run/mysqld/mysqld.sock
            user: c1typo3

MAIL:
    transport: sendmail
    transport_sendmail_command: '/usr/sbin/sendmail -t -i '
    transport_smtp_server: ''

EXTCONF:
    tp3_site:
            defaultLanguageDomain: web.tp3.de
            englishDomain: dev.tp3.de

SYS:
    caching:
        cacheConfigurations:
            extbase_object:
                backend: TYPO3\CMS\Core\Cache\Backend\ApcuBackend
    encryptionKey: 2eed5589614e589ec322bf048c3f41c114a63da325d6a3ff649ce581234fecfb5d7b0a22f0f9b8e260891e88ef9fafbe
    sitename: 'tp3 TYPO3 8 Suite'
