BE:
    installToolPassword: $pbkdf2-sha256$25000$dUP4NBFic9lMPOuYYzwLaw$FkLwE2H4CI3sNa5y0Nhba6X508gFegsnAUUMgnD2Zbo
DB:
    Connections:
        Default:
            dbname: c1_demo
            driver: mysqli
            host: 2.2.2.50
            password: zs1yOCf@U
            port: 3306
            unix_socket: /run/mysqld/mysqld.sock
            user: c1typo3

EXTCONF:
    tp3_site:
        defaultLanguageDomain: praxis.tp3.de
        englishDomain: praxis.tp3.de
SYS:
    caching:
        cacheConfigurations:
            extbase_object:
                backend: TYPO3\CMS\Core\Cache\Backend\ApcuBackend
    encryptionKey: 2eed5589614e589ec322bf048c3f41c114a63da325d6a3ff649ce581234fecfb5d7b0a22f0f9b8e260891e88ef9fafbe
    sitename: 'tp3 TYPO3 8 Suite'
