imports:
    - { resource: settings.yaml, exclude: [LOG] }

SYS:
    Objects:
        TYPO3\CMS\Core\Configuration\ConfigurationManager:
            className: 'Helhum\TYPO3\ConfigHandling\Xclass\ConfigurationManager'
        TYPO3\CMS\Install\Controller\Action\Tool\AllConfiguration:
            className: 'Helhum\TYPO3\ConfigHandling\Xclass\AllConfiguration'
BE:
    sessionTimeout: 31536000
    installToolPassword: $pbkdf2-sha256$25000$IOPdo.v8l7ClE.xzD2VrjA$ve2ttFyoKfOpg4ft4hAQJZwGYklF9TwIuWhDFBseABQ
DB:
    Connections:
        Default:
            dbname: c1typo3
            driver: mysqli
            host: 2.2.2.50
            password: zs1yOCf@U
            port: 3306
            unix_socket: /run/mysqld/mysqld.sock
            user: c1typo3
EXTCONF:
    tp3_site:
            defaultLanguageDomain: www.srt-wiesbaden.de
            englishDomain: srt-wiesbaden.de
    srt_site:
            defaultLanguageDomain: www.srt-ledermoebelreinigung.de
            englishDomain: srt-ledermoebelreinigung.de
MAIL:
    transport: sendmail
    transport_sendmail_command: '/usr/sbin/sendmail -t -i '
    transport_smtp_server: ''
