imports:
    - { resource: DefaultConfiguration, type: typo3, exclude: [LOG] }
    - { resource: 'includes/*.yaml', type: glob }
    - { resource: '../Packages/*/Configuration/Distribution/*.yaml', type: glob, ignore_errors: true }
    - { resource: local.settings.yaml }

BE:
    explicitADmode: explicitAllow
    loginSecurityLevel: rsa
DB:
    Connections:
        Default:
            charset: utf8
EXTCONF:
    lang:
        availableLanguages:
            - de
FE:
    addRootLineFields: 'subtitle,author,keywords,description,media,title,abstract,tsconfig'
    loginSecurityLevel: normal
GFX:
    jpg_quality: '80'
    processor: GraphicsMagick
    processor_effects: -1
LOG:
    writerConfiguration:
        '%const(TYPO3\CMS\Core\Log\LogLevel::WARNING)%':
            TYPO3\CMS\Core\Log\Writer\FileWriter:
                logFile: '%env(TYPO3_PATH_COMPOSER_ROOT)%/var/log/typo3-warning.log'
SYS:
    displayErrors: 0
    errorHandlerErrors: 1
    exceptionalErrors: 1
    reverseProxyIP: 2.2.2.2
    systemLogLevel: 2
