EXTCONF:
    realurl:
        _DOMAINS:
            encode:

                - { GETvar: L, value: '0', useConfiguration: tp3_site.tld, urlPrepend: 'http://%conf(EXTCONF.tp3_site.defaultLanguageDomain)%' }
                - { GETvar: L, value: '0', useConfiguration: bettina-mackeprang.de, urlPrepend: 'http://%conf(EXTCONF.bettina_mackeprang.defaultLanguageDomain)%' }
                - { GETvar: L, value: '0', useConfiguration: honda-lorenz.de, urlPrepend: 'http://%conf(EXTCONF.honda_lorenz.defaultLanguageDomain)%' }
                - { GETvar: L, value: '0', useConfiguration: lacuisine.de, urlPrepend: 'http://%conf(EXTCONF.lacuisine.defaultLanguageDomain)%' }
                - { GETvar: L, value: '0', useConfiguration: tai-chi.tp3.de, urlPrepend: 'http://%conf(EXTCONF.tai_chi.defaultLanguageDomain)%' }
                - { GETvar: L, value: '0', useConfiguration: dev_rp.tld, urlPrepend: 'http://%conf(EXTCONF.dev_rp.defaultLanguageDomain)%' }
                - { GETvar: L, value: '0', useConfiguration: test_rp.tld, urlPrepend: 'http://%conf(EXTCONF.test_rp.defaultLanguageDomain)%' }
                - { GETvar: L, value: '1', useConfiguration: tp3_site.tld, urlPrepend: 'http://%conf(EXTCONF.tp3_site.defaultLanguageDomain)%' }
                - { GETvar: L, value: '1', useConfiguration: bettina-mackeprang.de, urlPrepend: 'http://%conf(EXTCONF.bettina_mackeprang.defaultLanguageDomain)%' }
                - { GETvar: L, value: '1', useConfiguration: honda-lorenz.de, urlPrepend: 'http://%conf(EXTCONF.honda_lorenz.defaultLanguageDomain)%' }
                - { GETvar: L, value: '1', useConfiguration: lacuisine.de, urlPrepend: 'http://%conf(EXTCONF.lacuisine.defaultLanguageDomain)%' }
                - { GETvar: L, value: '1', useConfiguration: tai-chi.tp3.de, urlPrepend: 'http://%conf(EXTCONF.tai_chi.defaultLanguageDomain)%' }
                - { GETvar: L, value: '1', useConfiguration: dev_rp.tld, urlPrepend: 'http://%conf(EXTCONF.dev_rp.defaultLanguageDomain)%' }
                - { GETvar: L, value: '1', useConfiguration: test_rp.tld, urlPrepend: 'http://%conf(EXTCONF.test_rp.defaultLanguageDomain)%' }
                - { GETvar: L, value: '2', useConfiguration: test_rp.tld, urlPrepend: 'http://%conf(EXTCONF.test_rp.defaultLanguageDomain)%' }
                - { GETvar: L, value: '2', useConfiguration: tp3_site.tld, urlPrepend: 'http://%conf(EXTCONF.tp3_site.englishDomain)%' }
                - { GETvar: L, value: '2', useConfiguration: bettina-mackeprang.de, urlPrepend: 'http://%conf(EXTCONF.bettina_mackeprang.englishDomain)%' }
                - { GETvar: L, value: '2', useConfiguration: honda-lorenz.de, urlPrepend: 'http://%conf(EXTCONF.honda_lorenz.englishDomain)%' }
                - { GETvar: L, value: '2', useConfiguration: lacuisine.de, urlPrepend: 'http://%conf(EXTCONF.lacuisine.englishDomain)%' }
                - { GETvar: L, value: '2', useConfiguration: tai-chi.tp3.de, urlPrepend: 'http://%conf(EXTCONF.tai_chi.englishDomain)%' }
                - { GETvar: L, value: '2', useConfiguration: dev_rp.tld, urlPrepend: 'http://%conf(EXTCONF.dev_rp.englishDomain)%' }
                - { GETvar: L, value: '2', useConfiguration: test_rp.tld, urlPrepend: 'http://%conf(EXTCONF.test_rp.englishDomain)%' }
                - { GETvar: L, value: '2', useConfiguration: default.tld, urlPrepend: 'http://%conf(EXTCONF.helhum_site_package.englishDomain)%' }

            decode:
                '%conf(EXTCONF.tp3_site.defaultLanguageDomain)%':
                    GETvars: { L: '0' }
                    useConfiguration: tp3_site.tld
                '%conf(EXTCONF.bettina_mackeprang.defaultLanguageDomain)%':
                    GETvars: { L: '0' }
                    useConfiguration: bettina-mackeprang.de
                '%conf(EXTCONF.honda_lorenz.defaultLanguageDomain)%':
                    GETvars: { L: '0' }
                    useConfiguration: honda-lorenz.de
                '%conf(EXTCONF.lacuisine.defaultLanguageDomain)%':
                    GETvars: { L: '0' }
                    useConfiguration: lacuisine.de
                '%conf(EXTCONF.tai_chi.defaultLanguageDomain)%':
                    GETvars: { L: '0' }
                    useConfiguration: tai-chi.tp3.de
                '%conf(EXTCONF.dev_rp.defaultLanguageDomain)%':
                    GETvars: { L: '0' }
                    useConfiguration: dev.r-p-it.com
                '%conf(EXTCONF.tp3_site.englishDomain)%':
                    GETvars: { L: '2' }
                    useConfiguration: default.tld
                '%conf(EXTCONF.bettina_mackeprang.englishDomain)%':
                    GETvars: { L: '2' }
                    useConfiguration: bettina-mackeprang.de
                '%conf(EXTCONF.honda_lorenz.englishDomain)%':
                    GETvars: { L: '2' }
                    useConfiguration: honda-lorenz.de
                '%conf(EXTCONF.lacuisine.englishDomain)%':
                    GETvars: { L: '2' }
                    useConfiguration: lacuisine.de
                '%conf(EXTCONF.tai_chi.englishDomain)%':
                    GETvars: { L: '2' }
                    useConfiguration: tai-chi.tp3.de
                '%conf(EXTCONF.dev_rp.englishDomain)%':
                    GETvars: { L: '2' }
                    useConfiguration: dev.r-p-it.com


        default.tld:
            init:
                enableCHashCache: true
                appendMissingSlash: 'ifNotFile'
                adminJumpToBackend: true
                enableUrlDecodeCache: true
                enableUrlEncodeCache: true
                emptyUrlReturnValue: /
                disableErrorLog: true
            pagePath:
                rootpage_id: '690'
                type: user
                userFunc: 'Tx\Realurl\UriGeneratorAndResolver->main'
                spaceCharacter: '-'
                languageGetVar: 'L'
                expireDays: 3
                dontResolveShortcuts: false
            fileName:
                defaultToHTMLsuffixOnPrev: false
        bettina-mackeprang.de:
            init:
                enableCHashCache: true
                appendMissingSlash: 'ifNotFile'
                adminJumpToBackend: true
                enableUrlDecodeCache: true
                enableUrlEncodeCache: true
                emptyUrlReturnValue: /
                disableErrorLog: true
            pagePath:
                rootpage_id: '1140'
                type: user
                userFunc: 'Tx\Realurl\UriGeneratorAndResolver->main'
                spaceCharacter: '-'
                languageGetVar: 'L'
                expireDays: 3
                dontResolveShortcuts: false
            fileName:
                defaultToHTMLsuffixOnPrev: false
        honda-lorenz.de:
            init:
                enableCHashCache: true
                appendMissingSlash: 'ifNotFile'
                adminJumpToBackend: true
                enableUrlDecodeCache: true
                enableUrlEncodeCache: true
                emptyUrlReturnValue: /
                disableErrorLog: true
            pagePath:
                rootpage_id: '956'
                type: user
                userFunc: 'Tx\Realurl\UriGeneratorAndResolver->main'
                spaceCharacter: '-'
                languageGetVar: 'L'
                expireDays: 3
                dontResolveShortcuts: false
            fileName:
                defaultToHTMLsuffixOnPrev: false
        lacuisine.de:
            init:
                enableCHashCache: true
                appendMissingSlash: 'ifNotFile'
                adminJumpToBackend: true
                enableUrlDecodeCache: true
                enableUrlEncodeCache: true
                emptyUrlReturnValue: /
                disableErrorLog: true
            pagePath:
                rootpage_id: '690'
                type: user
                userFunc: 'Tx\Realurl\UriGeneratorAndResolver->main'
                spaceCharacter: '-'
                languageGetVar: 'L'
                expireDays: 3
                dontResolveShortcuts: false
            fileName:
                defaultToHTMLsuffixOnPrev: false
        tai-chi.tp3.de:
            init:
                enableCHashCache: true
                appendMissingSlash: 'ifNotFile'
                adminJumpToBackend: true
                enableUrlDecodeCache: true
                enableUrlEncodeCache: true
                emptyUrlReturnValue: /
                disableErrorLog: true
            pagePath:
                rootpage_id: '168'
                type: user
                userFunc: 'Tx\Realurl\UriGeneratorAndResolver->main'
                spaceCharacter: '-'
                languageGetVar: 'L'
                expireDays: 3
                dontResolveShortcuts: false
            fileName:
                defaultToHTMLsuffixOnPrev: false
        dev.r-p-it.com:
            init:
                enableCHashCache: true
                appendMissingSlash: 'ifNotFile'
                adminJumpToBackend: true
                enableUrlDecodeCache: true
                enableUrlEncodeCache: true
                emptyUrlReturnValue: /
                disableErrorLog: true
            pagePath:
                rootpage_id: '104'
                type: user
                userFunc: 'Tx\Realurl\UriGeneratorAndResolver->main'
                spaceCharacter: '-'
                languageGetVar: 'L'
                expireDays: 3
                dontResolveShortcuts: false
            fileName:
                defaultToHTMLsuffixOnPrev: false
        test.r-p-it.com:
            init:
                enableCHashCache: true
                appendMissingSlash: 'ifNotFile'
                adminJumpToBackend: true
                enableUrlDecodeCache: true
                enableUrlEncodeCache: true
                emptyUrlReturnValue: /
                disableErrorLog: true
            pagePath:
                rootpage_id: '37'
                type: user
                userFunc: 'Tx\Realurl\UriGeneratorAndResolver->main'
                spaceCharacter: '-'
                languageGetVar: 'L'
                expireDays: 3
                dontResolveShortcuts: false
            fileName:
                defaultToHTMLsuffixOnPrev: false
        localdev.tp3.de:
            init:
                enableCHashCache: true
                appendMissingSlash: 'ifNotFile'
                adminJumpToBackend: true
                enableUrlDecodeCache: true
                enableUrlEncodeCache: true
                emptyUrlReturnValue: /
                disableErrorLog: true
            pagePath:
                rootpage_id: '1'
                type: user
                userFunc: 'Tx\Realurl\UriGeneratorAndResolver->main'
                spaceCharacter: '-'
                languageGetVar: 'L'
                expireDays: 3
                dontResolveShortcuts: false
            fileName:
                defaultToHTMLsuffixOnPrev: false
        '%conf(EXTCONF.tp3_site.defaultLanguageDomain)%': 'default.tld'
        '%conf(EXTCONF.bettina_mackeprang.defaultLanguageDomain)%': 'bettina-mackeprang.de'
        '%conf(EXTCONF.honda_lorenz.defaultLanguageDomain)%': 'honda-lorenz.de'
        '%conf(EXTCONF.lacuisine.defaultLanguageDomain)%': 'lacuisine.de'
        '%conf(EXTCONF.tai_chi.defaultLanguageDomain)%': 'tai_chi.tld'
        '%conf(EXTCONF.dev_rp.defaultLanguageDomain)%': 'dev.r-p-it.com'
        '%conf(EXTCONF.test_rp.defaultLanguageDomain)%': 'test.r-p-it.com'
        '%conf(EXTCONF.tp3_site.englishDomain)%': 'default.tld'
        '%conf(EXTCONF.bettina_mackeprang.englishDomain)%': 'bettina_mackeprang.de'
        '%conf(EXTCONF.honda_lorenz.englishDomain)%': 'honda-lorenz.de'
        '%conf(EXTCONF.lacuisine.englishDomain)%': 'lacuisine.de'
        '%conf(EXTCONF.tai_chi.englishDomain)%': 'tai_chi.tld'
        '%conf(EXTCONF.dev_rp.englishDomain)%': 'dev.r-p-it.com'
        '%conf(EXTCONF.test_rp.englishDomain)%': 'test.r-p-it.com'
