EXTCONF:
    realurl:
        _DOMAINS:
            encode:
                - { GETvar: L, value: '0', useConfiguration: default.tld, urlPrepend: 'http://%conf(EXTCONF.tp3_site.defaultLanguageDomain)%' }
                - { GETvar: L, value: '2', useConfiguration: default.tld, urlPrepend: 'http://%conf(EXTCONF.tp3_site.defaultLanguageDomain)%/en/' }
                - { GETvar: L, value: '0', useConfiguration: srt.tld, urlPrepend: 'http://%conf(EXTCONF.tp3_site.defaultLanguageDomain)%' }
                - { GETvar: L, value: '2', useConfiguration: srt.tld, urlPrepend: 'http://%conf(EXTCONF.tp3_site.defaultLanguageDomain)%/en/' }

            decode:
                '%conf(EXTCONF.tp3_site.defaultLanguageDomain)%':
                    GETvars: { L: '0' }
                    useConfiguration: default.tld

                '%conf(EXTCONF.tp3_site.englishDomain)%':
                    GETvars: { L: '2' }
                    useConfiguration: default.tld

        default.tld:
            init:
                enableCHashCache: true
                appendMissingSlash: 'ifNotFile'
                adminJumpToBackend: true
                enableUrlDecodeCache: true
                enableUrlEncodeCache: true
                emptyUrlReturnValue: /
                disableErrorLog: true
                postVarSet_failureMode: 'redirect_goodUpperDir'
            pagePath:
                rootpage_id: '710'
                type: user
                userFunc: 'Tx\Realurl\UriGeneratorAndResolver->main'
                spaceCharacter: '-'
                languageGetVar: 'L'
                expireDays: 3
                dontResolveShortcuts: false
            fileName:
                defaultToHTMLsuffixOnPrev: false
        leder.tld:
            init:
                enableCHashCache: true
                appendMissingSlash: 'ifNotFile'
                adminJumpToBackend: true
                enableUrlDecodeCache: true
                enableUrlEncodeCache: true
                emptyUrlReturnValue: /
                disableErrorLog: true
                postVarSet_failureMode: 'redirect_goodUpperDir'
            pagePath:
                rootpage_id: '728'
                type: user
                userFunc: 'Tx\Realurl\UriGeneratorAndResolver->main'
                spaceCharacter: '-'
                languageGetVar: 'L'
                expireDays: 3
                dontResolveShortcuts: false
            fileName:
                defaultToHTMLsuffixOnPrev: false

        '%conf(EXTCONF.tp3_site.defaultLanguageDomain)%': 'default.tld'
        '%conf(EXTCONF.tp3_site.englishDomain)%': 'default.tld'

