# .travis.yml
language: php

branches:
  only:
  - master

matrix:
  fast_finish: true
  include:
  - php: 7.0
    env: TYPO3_VERSION=^8.7
  - php: 7.1
    env: TYPO3_VERSION=^8.7
  - php: 7.0
    env: TYPO3_VERSION=dev-master
  - php: 7.1
    env: TYPO3_VERSION=dev-master

sudo: false

addons:
  ssh_known_hosts:
  - bootstrap-package.com
  apt:
    packages:
    - parallel

cache:
  directories:
  - $HOME/.composer/cache

before_install:
- phpenv config-rm xdebug.ini
- composer self-update
- composer --version

before_script:
- composer require typo3/cms="$TYPO3_VERSION"
- export TYPO3_PATH_WEB="$PWD/.build/web"

script:
- >
  echo;
  echo "Running php lint";
  find . -name \*.php ! -path "./.build/*" | parallel --gnu php -d display_errors=stderr -l {} > /dev/null \;
- >
  echo;
  echo "Running php-cs-fixer";
  .build/bin/php-cs-fixer --diff --dry-run -v fix
- >
  echo "Installing npm modules";
  pushd Build;
  npm install && npm install grunt-cli;
  echo "Executing grunt";
  node_modules/.bin/grunt;
  popd