language: php

dist: noble

php:
  - 8.1
  - 8.2
  - 8.3

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer self-update || true

install:
  - composer install --no-interaction --prefer-dist

script:
  - echo
  - echo "Validate composer"
  - composer validate --no-check-publish

  - echo
  - echo "Running unit tests"
  - vendor/bin/phpunit tests/Unit --log-junit build/logs/junit-unit.xml

notifications:
  slack:
    rooms:
      - tp3-web:e5IFnyCMfPVKXAnYL2D3dOqe#code
