image: webtp3/typo3:16.4-stable
options:
  docker: true
pipelines:
  default:

    - step:
        name: Deploy to testing
        deployment: test
        image: docker:stable
        caches:
          - composer
        script:
        deployment: test
        script:
          # for database start with composer
          - ls -an
         # - apk add --no-cache py-pip bash
         # - pip install --no-cache-dir docker-compose
         # - docker-compose -f docker-compose.yml up
          #- docker cp /opt/atlassian/pipelines/agent/build/ typo3:/var/www/html
          #- rsync -a /opt/atlassian/pipelines/agent/build/ /var/www/html
          - ls -an /opt/atlassian/pipelines/agent/build/
          - docker run -d -e MYSQL_ROOT_PASSWORD="my-secret-pw" --name db -p 3306:3306 webtp3/tp3sql
         # - docker build -t yourtest .
         #switch to autobuild save pipline time
          - docker login --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD
          - docker run -d  --rm -it -v $PWD:/build --link db:db -e DB_PASS="my-secret-pw" -p 80:80  -p 2222:22 -p 443:443 -p 9000:9000   --name typo3 thomasruta/tp3_tests

          - docker exec typo3 composer config  repositories.local path 'Packages/*' -d  /var/www/html/
          - docker exec typo3 composer --dev install -d  /var/www/html/
          - docker exec typo3 ln -s  ../vendor /var/www/html/web/vendor
            #automated install will fail! thats because the /var/run/mysql.sock is not available
            #-> run-typo3.sh will fix that by linking the mysql container
            #- docker exec typo3 bash /var/www/cgi-bin/run-typo3.sh
          # start testing
          - docker exec typo3 php vendor/phpunit/phpunit/phpunit --configuration web/typo3conf/ext/cag_tests/Tests/Build/UnitTests.xml --teamcity --log-junit UnitTests.log
          - docker exec typo3 php vendor/phpunit/phpunit/phpunit --configuration web/typo3conf/ext/cag_tests/Tests/Build/UnitTestsDeprecated.xml --teamcity --log-junit UnitTestsDeprecated.log
          - docker exec typo3 php vendor/phpunit/phpunit/phpunit --configuration web/typo3conf/ext/cag_tests/Tests/Build/FunctionalTests.xml --teamcity --log-junit FunctionalTests.log
          - docker exec typo3 mkdir -p web/typo3temp/var/tests
          - docker exec typo3 vendor/bin/chromedriver --url-base=/wd/hub >/dev/null 2>&1 &
          - docker exec typo3 php -S 0.0.0.0:8000 >/dev/null 2>&1 &
          - docker exec typo3 sleep 3;
          - docker exec typo3 typo3DatabaseName='typo3' typo3DatabaseHost='db' typo3DatabaseUsername='root' typo3DatabasePassword='my-secret-pw' vendor/codeception/codeception/codecept run Acceptance -c web/typo3conf/ext/cag_tests/Tests/Build/AcceptanceTests.yml


          - docker-compose -f docker-compose.yml down
definitions:
  services:
    docker:
      memory: 2048
