image: webtp3/docker:16.4-stable

pipelines:
  default:
    - step:
        name: Deploy to testing
        deployment: test
        image: webtp3/docker:16.4-stable
        caches:
          - composer
        script:
          - apt-get update && apt-get upgrade -y
          - rm -R /var/www/html -rf
          - cd /var/www/
          # start composer install
          - composer config repositories.local path 'Packages/*'
          - composer --dev install

          # start typo3 install from env
          - bash /var/www/cgi-bin/run-typo3.sh
          # start testing
          - php vendor/phpunit/phpunit/phpunit --configuration web/typo3conf/ext/cag_tests/Tests/Build/UnitTests.xml --teamcity
          - php vendor/phpunit/phpunit/phpunit --configuration web/typo3conf/ext/cag_tests/Tests/Build/UnitTestsDeprecated.xml --teamcity
          - php vendor/phpunit/phpunit/phpunit --configuration web/typo3conf/ext/cag_tests/Tests/Build/FunctionalTests.xml --teamcity
          - mkdir -p web/typo3temp/var/tests
          - ./bin/chromedriver --url-base=/wd/hub >/dev/null 2>&1 &
          - php -S 0.0.0.0:8000 >/dev/null 2>&1 &
          - sleep 3;
          - typo3DatabaseName='typo3' typo3DatabaseHost='DB' typo3DatabaseUsername='root' typo3DatabasePassword='my-secret-pw' vendor/codeception/codeception/codecept run Acceptance -c web/typo3conf/ext/cag_tests/Tests/Build/AcceptanceTests.yml


    - step:
        name: Deploy to staging
        image: php:7.1.1
        deployment: staging
        trigger: manual
        script:
          - python deploy.py staging
    - step:
        name: Deploy to production
        image: aneitayang/aws-cli:1.0
        deployment: production
        trigger: manual
        script:
          - python deploy.py prod