typo3:
  image: webtp3/typo3:16.4-bundle

  ports:
   - 80:80
   - 443:443
   - 2222:22
   - 9000:9000
   - 3306:3306

  environment:
    DB_NAME: typo3
    DB_USER: root
    DB_PASS: my-secret-pw
    DB_HOST: localhost
    DB_PORT: 3306
    MYSQL_ROOT_PASSWORD: my-secret-pw



adminer:
  image: adminer
  restart: always
  links:
    - typo3
  ports:
    - 8080:8080