<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "tp3_businessview"
 *
 * Auto generated by Extension Builder 2015-12-01
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'BusinsessView',
	'description' => 'google businessview für tp3',
	'category' => 'plugin',
	'author' => 'Thomas Ruta',
	'author_email' => 'support@r-p-it.de',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);