<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "tp3_businessview"
 *
 * Auto generated by Extension Builder 2018-03-27
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'BusinsessView',
    'description' => 'google businessview für tp3',
    'category' => 'plugin',
    'author' => 'Thomas Ruta',
    'author_email' => 'support@r-p-it.de',
    'state' => 'alpha',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '0.0.3',
    'constraints' => [
        'depends' => [
            'typo3' => '7.6.* - 8.9.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
