<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "cag_tests"
 *
 * Auto generated by Extension Builder 2018-06-22
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Basic functional Tests',
    'description' => 'Some Std Tests like login FE,BE. Scripting Errors and more',
    'category' => 'misc',
    'author' => 'Thomas Ruta, Jochen Rieger',
    'author_email' => 'email@thomasruta.de, j.rieger@connecta.ag',
    'state' => 'alpha',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '7.6.0-8.9.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
