# list servers
# -------------
dev:
    hostname: localdev.tp3.de
    port: 22
    user: 'tr'
    public_key:  '~/.ssh/id_rsa.pub'
    private_key: '~/.ssh/id_rsa'
    password:    'jpb0OIJlmCmiRT9hP5Pu'

    configFile: config/keys/ssh_config
    identityFile: config/keys/id_rsa
    forwardAgent: true
    multiplexing: true
    stage: dev
    deploy_path: /develop/dev-rp/private/
    typo3_webroot: ../web/
    #// Project path
    application: /tmp

    #// Project repository
    repository: git@bitbucket.org:web-tp3/dev-rp.git
    git_tty: true
    keep_releases: 4

    #// Shared files/dirs between deploys
    shared_files: ['.env','config/local.settings.yaml','web/typo3conf/realurl_conf.php','web/typo3conf/LocalConfiguration.php','web/typo3conf/AdditionalConfiguration.php','web/typo3conf/PackageStates.php']
    shared_dirs: ['web/fileadmin','web/typo3temp','web/uploads','web/typo3conf/l10n','var']

    #// Writable dirs by web server
    writable_dirs: ['../tmp/','_temp', 'web/fileadmin','web/typo3temp','web/typo3conf','web/uploads','var']
    branch: 8.x-dev

stage:
    hostname: praxis.tp3.de
    port: 22
    user: r_p_it_praxis
    public_key:  'config/keys/id_rsa.pub'
    private_key: 'config/keys/id_rsa'
    password:    'jpb0OIJlmCmiRT9hP5Pu'
    configFile: config/keys/ssh_config
    slack_suffix: TBBV2KZCL/BJ21YU7SN/tDANrimaAskvTBENchW234Iq
    identityFile: config/keys/id_rsa
    forwardAgent: true
    multiplexing: true
    stage: develop
    sshOptions:
      UserKnownHostsFile: /dev/null
      StrictHostKeyChecking: no
    deploy_path: /var/www/praxis.tp3.de/private/
    typo3_webroot: ../web/
    branch: 8.x-dev
    #// Project path
    application: tmp/

    #// Project repository
    repository: git@bitbucket.org:web-tp3/dev-rp.git
    git_tty: true
    keep_releases: 2

    #// Shared files/dirs between deploys
    shared_files: ['.env','config/local.settings.yaml','web/typo3conf/realurl_conf.php','web/typo3conf/LocalConfiguration.php','web/typo3conf/AdditionalConfiguration.php','web/typo3conf/PackageStates.php']
    shared_dirs: ['web/fileadmin','web/typo3temp','web/uploads','web/typo3conf/l10n','var']

    #// Writable dirs by web server
    writable_dirs: ['../tmp/','_temp', 'web/fileadmin','web/typo3temp','web/typo3conf','web/uploads','var']

toasternet:
    hostname: toasternet.eu
    port: 22
    user: toaster_www
    public_key:  'config/keys/id_rsa.pub'
    private_key: 'config/keys/id_rsa'
    password:    'jpb0OIJlmCmiRT9hP5Pu'
    configFile: config/keys/ssh_config
    slack_suffix: TBBV2KZCL/BJ21YU7SN/tDANrimaAskvTBENchW234Iq
    identityFile: config/keys/id_rsa
    forwardAgent: true
    multiplexing: true
    stage: production
    sshOptions:
      UserKnownHostsFile: /dev/null
      StrictHostKeyChecking: no
    deploy_path: /var/www/toasternet.eu/private/
    typo3_webroot: ../web/
    branch: 8.x-dev
    #// Project path
    application: tmp/

    #// Project repository
    repository: git@bitbucket.org:web-tp3/dev-rp.git
    git_tty: true
    keep_releases: 2

    #// Shared files/dirs between deploys
    shared_files: ['.env','config/local.settings.yaml','web/typo3conf/realurl_conf.php','web/typo3conf/LocalConfiguration.php','web/typo3conf/AdditionalConfiguration.php','web/typo3conf/PackageStates.php']
    shared_dirs: ['web/fileadmin','web/typo3temp','web/uploads','web/typo3conf/l10n','var']

    #// Writable dirs by web server
    writable_dirs: ['web/fileadmin','web/typo3temp','web/typo3conf','web/uploads','var']

dnadirekt:
    hostname: vaterschaftstest.tp3.de
    port: 22
    user: toaster_dnsdirekt
    public_key:  'config/keys/id_rsa.pub'
    private_key: 'config/keys/id_rsa'
    password:    ''
    configFile: config/keys/ssh_config
    slack_suffix: TBBV2KZCL/BJ21YU7SN/tDANrimaAskvTBENchW234Iq
    identityFile: config/keys/id_rsa
    forwardAgent: true
    multiplexing: true
    stage: production
    sshOptions:
      UserKnownHostsFile: /dev/null
      StrictHostKeyChecking: no
    deploy_path: /var/www/vaterschaftstest.tp3.de/private/
    typo3_webroot: ../web/
    branch: 8.x-dev
    #// Project path
    application: tmp/

    #// Project repository
    repository: git@bitbucket.org:web-tp3/dev-rp.git
    git_tty: true
    keep_releases: 2

    #// Shared files/dirs between deploys
    shared_files: ['.env','config/local.settings.yaml','web/typo3conf/realurl_conf.php','web/typo3conf/LocalConfiguration.php','web/typo3conf/AdditionalConfiguration.php','web/typo3conf/PackageStates.php']
    shared_dirs: ['web/fileadmin','web/typo3temp','web/uploads','web/typo3conf/l10n','var']

    #// Writable dirs by web server
    writable_dirs: ['web/fileadmin','web/typo3temp','web/typo3conf','web/uploads','var']

devtoasternet:
    hostname: dev.toasternet.eu
    port: 22
    user: toaster_ssh
    public_key:  'config/keys/id_rsa.pub'
    private_key: 'config/keys/id_rsa'
    password:    'jpb0OIJlmCmiRT9hP5Pu'
    configFile: config/keys/ssh_config
    slack_suffix: TBBV2KZCL/BJ21YU7SN/tDANrimaAskvTBENchW234Iq
    identityFile: config/keys/id_rsa
    forwardAgent: true
    multiplexing: true
    stage: production
    sshOptions:
      UserKnownHostsFile: /dev/null
      StrictHostKeyChecking: no
    deploy_path: /var/www/dev.toasternet.eu/private/
    typo3_webroot: ../web/
    branch: 8.x-dev
    #// Project path
    application: tmp/

    #// Project repository
    repository: git@bitbucket.org:web-tp3/dev-rp.git
    git_tty: true
    keep_releases: 2

    #// Shared files/dirs between deploys
    shared_files: ['.env','config/local.settings.yaml','web/typo3conf/realurl_conf.php','web/typo3conf/LocalConfiguration.php','web/typo3conf/AdditionalConfiguration.php','web/typo3conf/PackageStates.php']
    shared_dirs: ['web/fileadmin','web/typo3temp','web/uploads','web/typo3conf/l10n','var']

    #// Writable dirs by web server
    writable_dirs: ['web/fileadmin','web/typo3temp','web/typo3conf','web/uploads','var']

lacuisine:
    hostname: test.lacuisine.de
    port: 22
    user: lacuisine_composer
    public_key:  'config/keys/id_rsa.pub'
    private_key: 'config/keys/id_rsa'
    password:    'jpb0OIJlmCmiRT9hP5Pu'
    configFile: config/keys/ssh_config
    slack_suffix: TBBV2KZCL/BJ21YU7SN/tDANrimaAskvTBENchW234Iq
    identityFile: config/keys/id_rsa
    forwardAgent: true
    multiplexing: true
    stage: production
    deploy_path: /var/www/test.lacuisine.de/private/
    typo3_webroot: ../web/

    branch: 8.x-dev
    #// Project path
    application: tmp/

    #// Project repository
    repository: git@bitbucket.org:web-tp3/dev-rp.git
    git_tty: true
    keep_releases: 2

    #// Shared files/dirs between deploys
    shared_files: ['.env','config/local.settings.yaml','web/typo3conf/realurl_conf.php','web/typo3conf/LocalConfiguration.php','web/typo3conf/AdditionalConfiguration.php','web/typo3conf/PackageStates.php']
    shared_dirs: ['web/fileadmin','web/typo3temp','web/uploads','web/typo3conf/l10n','var']

    #// Writable dirs by web server
    writable_dirs: ['../tmp/','_temp', 'web/fileadmin','web/typo3temp','web/typo3conf','web/uploads','var']


lacuisine_dev:
    hostname: dev.lacuisine.de
    port: 22
    user: lacuisine_dev
    public_key:  'config/keys/id_rsa.pub'
    private_key: 'config/keys/id_rsa'
    password:    'jpb0OIJlmCmiRT9hP5Pu'
    configFile: config/keys/ssh_config
    slack_suffix: TBBV2KZCL/BJ21YU7SN/tDANrimaAskvTBENchW234Iq
    identityFile: config/keys/id_rsa
    forwardAgent: true
    multiplexing: true
    stage: production
    deploy_path: /var/www/dev.lacuisine.de/private/
    typo3_webroot: ../web/

    branch: 8.x-dev
    #// Project path
    application: tmp/

    #// Project repository
    repository: git@bitbucket.org:web-tp3/dev-rp.git
    git_tty: true
    keep_releases: 2

    #// Shared files/dirs between deploys
    shared_files: ['.env','config/local.settings.yaml','web/typo3conf/realurl_conf.php','web/typo3conf/LocalConfiguration.php','web/typo3conf/AdditionalConfiguration.php','web/typo3conf/PackageStates.php']
    shared_dirs: ['web/fileadmin','web/typo3temp','web/uploads','web/typo3conf/l10n','var']

    #// Writable dirs by web server
    writable_dirs: ['../tmp/','_temp', 'web/fileadmin','web/typo3temp','web/typo3conf','web/uploads','var']


tr:
    hostname: dev.thomasruta.de
    port: 22
    user: thomasruta_tudy
    public_key:  'config/keys/id_rsa.pub'
    private_key: 'config/keys/id_rsa'
    password:    'jpb0OIJlmCmiRT9hP5Pu'
    configFile: config/keys/ssh_config
    slack_suffix: TBBV2KZCL/BJ21YU7SN/tDANrimaAskvTBENchW234Iq
    identityFile: config/keys/id_rsa
    forwardAgent: true
    multiplexing: true
    stage: production
    deploy_path: /var/www/dev.thomasruta.de/private/
    typo3_webroot: ../web/

    branch: 8.x-dev
    #// Project path
    application: tmp/

    #// Project repository
    repository: git@bitbucket.org:web-tp3/dev-rp.git
    git_tty: true
    keep_releases: 2

    #// Shared files/dirs between deploys
    shared_files: ['.env','config/local.settings.yaml','web/typo3conf/realurl_conf.php','web/typo3conf/LocalConfiguration.php','web/typo3conf/AdditionalConfiguration.php','web/typo3conf/PackageStates.php']
    shared_dirs: ['web/fileadmin','web/typo3temp','web/uploads','web/typo3conf/l10n','var']

    #// Writable dirs by web server
    writable_dirs: ['../tmp/','_temp', 'web/fileadmin','web/typo3temp','web/typo3conf','web/uploads','var']



cdu:
    hostname: old.r-p-it.com
    port: 22
    user: r_p_it_cdu
    public_key:  'config/keys/id_rsa.pub'
    private_key: 'config/keys/id_rsa'
    password:    'jpb0OIJlmCmiRT9hP5Pu'
    configFile: config/keys/ssh_config
    slack_suffix: TBBV2KZCL/BJ21YU7SN/tDANrimaAskvTBENchW234Iq
    identityFile: config/keys/id_rsa
    forwardAgent: true
    multiplexing: true
    stage: production
    deploy_path: /var/www/old.r-p-it.com/private/
    typo3_webroot: ../web/

    branch: 8.x-dev
    #// Project path
    application: tmp/

    #// Project repository
    repository: git@bitbucket.org:web-tp3/dev-rp.git
    git_tty: true
    keep_releases: 2

    #// Shared files/dirs between deploys
    shared_files: ['.env','config/local.settings.yaml','web/typo3conf/realurl_conf.php','web/typo3conf/LocalConfiguration.php','web/typo3conf/AdditionalConfiguration.php','web/typo3conf/PackageStates.php']
    shared_dirs: ['web/fileadmin','web/typo3temp','web/uploads','web/typo3conf/l10n','var']

    #// Writable dirs by web server
    writable_dirs: ['../tmp/','_temp', 'web/fileadmin','web/typo3temp','web/typo3conf','web/uploads','var']



rnn:
    hostname: rnn-web.de
    port: 22
    user: r_p_it_rnn
    public_key:  'config/keys/id_rsa.pub'
    private_key: 'config/keys/id_rsa'
    password:    'jpb0OIJlmCmiRT9hP5Pu'
    configFile: config/keys/ssh_config
    slack_suffix: TBBV2KZCL/BJ21YU7SN/tDANrimaAskvTBENchW234Iq
    identityFile: config/keys/id_rsa
    forwardAgent: true
    multiplexing: true
    stage: production
    deploy_path: /var/www/rnn-web.de/private/
    typo3_webroot: ../web/

    branch: 8.x-dev
    #// Project path1
    application: tmp

    #// Project repository
    repository: git@bitbucket.org:web-tp3/dev-rp.git
    git_tty: true
    keep_releases: 2

    #// Shared files/dirs between deploys
    shared_files: ['.env','config/local.settings.yaml','web/typo3conf/realurl_conf.php','web/typo3conf/LocalConfiguration.php','web/typo3conf/AdditionalConfiguration.php','web/typo3conf/PackageStates.php']
    shared_dirs: ['web/fileadmin','web/typo3temp','web/uploads','web/typo3conf/l10n','var']

    #// Writable dirs by web server
    writable_dirs: ['../tmp/','_temp', 'web/fileadmin','web/typo3temp','web/typo3conf','web/uploads','var']


tp3:
    hostname: dev.tp3.de
    port: 22
    user: r_p_it_tp3
    public_key:  '~/.ssh/id_rsa.pub'
    private_key: '~/.ssh//id_rsa'
    password:    'jpb0OIJlmCmiRT9hP5Pu'
    configFile: config/keys/ssh_config
    slack_suffix: TBBV2KZCL/BJ21YU7SN/tDANrimaAskvTBENchW234Iq
    identityFile: ~/.ssh/id_rsa
    forwardAgent: true
    multiplexing: true
    stage: production
    deploy_path: /var/www/dev.tp3.de/private/
    typo3_webroot: ../web/

    branch: 8.x-dev
    #// Project path
    application: tmp/

    #// Project repository
    repository: git@bitbucket.org:web-tp3/dev-rp.git
    git_tty: true
    keep_releases: 2

    #// Shared files/dirs between deploys
    shared_files: ['.env','config/local.settings.yaml','web/typo3conf/realurl_conf.php','web/typo3conf/LocalConfiguration.php','web/typo3conf/AdditionalConfiguration.php','web/typo3conf/PackageStates.php']
    shared_dirs: ['web/fileadmin','web/typo3temp','web/uploads','web/typo3conf/l10n','var']

    #// Writable dirs by web server
    writable_dirs: ['../tmp/','_temp', 'web/fileadmin','web/typo3temp','web/typo3conf','web/uploads','var']

rp:
    hostname: dev.r-p-it.com
    port: 22
    user: r_p_it_rp
    public_key:  'config/keys/id_rsa.pub'
    private_key: 'config/keys/id_rsa'
    password:    'jpb0OIJlmCmiRT9hP5Pu'
    configFile: config/keys/ssh_config
    slack_suffix: TBBV2KZCL/BJ21YU7SN/tDANrimaAskvTBENchW234Iq
    identityFile: config/keys/id_rsa
    forwardAgent: true
    multiplexing: true
    stage: production
    deploy_path: /var/www/dev.r-p-it.com/private/
    typo3_webroot: ../web/

    branch: 8.x-dev
    #// Project path
    application: tmp/

    #// Project repository
    repository: git@bitbucket.org:web-tp3/dev-rp.git
    git_tty: true
    keep_releases: 2

    #// Shared files/dirs between deploys
    shared_files: ['.env','config/local.settings.yaml','web/typo3conf/realurl_conf.php','web/typo3conf/LocalConfiguration.php','web/typo3conf/AdditionalConfiguration.php','web/typo3conf/PackageStates.php']
    shared_dirs: ['web/fileadmin','web/typo3temp','web/uploads','web/typo3conf/l10n','var']

    #// Writable dirs by web server
    writable_dirs: ['../tmp/','_temp', 'web/fileadmin','web/typo3temp','web/typo3conf','web/uploads','var']


srt:
    hostname: srt-wiesbaden.de
    port: 22
    user: srt_ssh
    public_key:  'config/keys/id_rsa.pub'
    private_key: 'config/keys/id_rsa'
    password:    'jpb0OIJlmCmiRT9hP5Pu'
    configFile: config/keys/ssh_config
    slack_suffix: TBBV2KZCL/BJ21YU7SN/tDANrimaAskvTBENchW234Iq
    identityFile: config/keys/id_rsa
    forwardAgent: true
    multiplexing: true
    stage: production
    deploy_path: /var/www/srt-sanierung.de/private/
    typo3_webroot: ../web/

    branch: 8.x-dev
    #// Project path
    application: tmp/

    #// Project repository
    repository: git@bitbucket.org:web-tp3/dev-rp.git
    git_tty: true
    keep_releases: 2

    #// Shared files/dirs between deploys
    shared_files: ['.env','config/local.settings.yaml','web/typo3conf/realurl_conf.php','web/typo3conf/LocalConfiguration.php','web/typo3conf/AdditionalConfiguration.php','web/typo3conf/PackageStates.php']
    shared_dirs: ['web/fileadmin','web/typo3temp','web/uploads','web/typo3conf/l10n','var']

   #// Writable dirs by web server
    writable_dirs: ['../tmp/','_temp', 'web/fileadmin','web/typo3temp','web/typo3conf','web/uploads','var']


yreim:
    hostname: yreim.de
    port: 22
    user: yreim_yreim
    public_key:  'config/keys/id_rsa.pub'
    private_key: 'config/keys/id_rsa'
    password:    'jpb0OIJlmCmiRT9hP5Pu'
    configFile: config/keys/ssh_config
    slack_suffix: TBBV2KZCL/BJ21YU7SN/tDANrimaAskvTBENchW234Iq
    identityFile: config/keys/id_rsa
    forwardAgent: true
    multiplexing: true
    stage: production
    deploy_path: /var/www/yreim.de/private/
    typo3_webroot: ../web/

    branch: 8.x-dev
    #// Project path
    application: tmp/

    #// Project repository
    repository: git@bitbucket.org:web-tp3/dev-rp.git
    git_tty: true
    keep_releases: 2

    #// Shared files/dirs between deploys
    shared_files: ['.env','config/local.settings.yaml','web/typo3conf/realurl_conf.php','web/typo3conf/LocalConfiguration.php','web/typo3conf/AdditionalConfiguration.php','web/typo3conf/PackageStates.php']
    shared_dirs: ['web/fileadmin','web/typo3temp','web/uploads','web/typo3conf/l10n','var']

    #// Writable dirs by web server
    writable_dirs: ['../tmp/','_temp', 'web/fileadmin','web/typo3temp','web/typo3conf','web/uploads','var']


laroe:
    hostname: kinderzahnarzt-badsoden.de
    port: 22
    user: laroe_ssh
    public_key:  'config/keys/id_rsa.pub'
    private_key: 'config/keys/id_rsa'
    password:    'jpb0OIJlmCmiRT9hP5Pu'
    configFile: config/keys/ssh_config
    slack_suffix: TBBV2KZCL/BJ21YU7SN/tDANrimaAskvTBENchW234Iq
    identityFile: config/keys/id_rsa
    forwardAgent: true
    multiplexing: true
    stage: production
    deploy_path: /var/www/kinderzauberzaehne.de/private/
    typo3_webroot: ../web/

    branch: 8.x-dev
    #// Project path
    application: tmp/

    #// Project repository
    repository: git@bitbucket.org:web-tp3/dev-rp.git
    git_tty: true
    keep_releases: 2

    #// Shared files/dirs between deploys
    shared_files: ['.env','config/local.settings.yaml','web/typo3conf/realurl_conf.php','web/typo3conf/LocalConfiguration.php','web/typo3conf/AdditionalConfiguration.php','web/typo3conf/PackageStates.php']
    shared_dirs: ['web/fileadmin','web/typo3temp','web/uploads','web/typo3conf/l10n','var']

    #// Writable dirs by web server
    writable_dirs: ['../tmp/','_temp', 'web/fileadmin','web/typo3temp','web/typo3conf','web/uploads','var']


sonnenberger:
  hostname: sonnenberger.tp3.de
  port: 22
  user: ig_sonnenberg_ssh
  public_key:  'config/keys/id_rsa.pub'
  private_key: 'config/keys/id_rsa'
  password:    'jpb0OIJlmCmiRT9hP5Pu'
  configFile: config/keys/ssh_config
  slack_suffix: TBBV2KZCL/BJ21YU7SN/tDANrimaAskvTBENchW234Iq
  identityFile: config/keys/id_rsa
  forwardAgent: true
  multiplexing: true
  stage: production
  deploy_path: /var/www/ig-sonnenberger-vereine.de/private/
  typo3_webroot: ../web/

  branch: 8.x-dev
  #// Project path
  application: tmp/

  #// Project repository
  repository: git@bitbucket.org:web-tp3/dev-rp.git
  git_tty: true
  keep_releases: 2

  #// Shared files/dirs between deploys
  shared_files: ['.env','config/local.settings.yaml','web/typo3conf/realurl_conf.php','web/typo3conf/LocalConfiguration.php','web/typo3conf/AdditionalConfiguration.php','web/typo3conf/PackageStates.php']
  shared_dirs: ['web/fileadmin','web/typo3temp','web/uploads','web/typo3conf/l10n','var']

  #// Writable dirs by web server
  writable_dirs: ['../tmp/','_temp', 'web/fileadmin','web/typo3temp','web/typo3conf','web/uploads','var']

