# list servers
# -------------
dev:
    hostname: localdev.tp3.de
    port: 22
    user: 'dev'
    public_key:  'config/keys/id_rsa.pub'
    private_key: 'config/keys/id_rsa'
    password:    'jpb0OIJlmCmiRT9hP5Pu'

    configFile: config/keys/ssh_config
    identityFile: config/keys/id_rsa
    forwardAgent: true
    multiplexing: true
    stage: dev
    deploy_path: /develop/dev-rp/private/
    typo3_webroot: ../web/
    #// Project path
    application: /tmp

    #// Project repository
    repository: https://thomasruta@bitbucket.org/web-tp3/dev-rp.git
    git_tty: true
    keep_releases: 4

    #// Shared files/dirs between deploys
    shared_files: ['.env','cag']
    shared_dirs: ['Build','config','bin','Libraries']

    #// Writable dirs by web server
    writable_dirs: ['../tmp/','_temp']
    branch: develop

stage:
    hostname: praxis.tp3.de
    port: 22
    user: r_p_it_praxis
    public_key:  'config/keys/id_rsa.pub'
    private_key: 'config/keys/id_rsa'
    password:    'jpb0OIJlmCmiRT9hP5Pu'
    configFile: config/keys/ssh_config
    identityFile: ''
    forwardAgent: true
    multiplexing: true
    stage: staging
    sshOptions:
      UserKnownHostsFile: /dev/null
      StrictHostKeyChecking: no
    deploy_path: /var/www/praxis.tp3.de/private/
    typo3_webroot: ../../../web/
    branch: develop
    #// Project path
    application: tmp/

    #// Project repository
    repository: https://thomasruta@bitbucket.org/web-tp3/dev-rp.git
    git_tty: true
    keep_releases: 4

    #// Shared files/dirs between deploys
    shared_files: ['.env']
    shared_dirs: ['config']

    #// Writable dirs by web server
    writable_dirs: ['../tmp/','_temp', 'web','var']

lacuisine:
    hostname: test.lacuisine.de
    port: 22
    user: lacuisine_composer
    public_key:  'config/keys/id_rsa.pub'
    private_key: 'config/keys/id_rsa'
    password:    'jpb0OIJlmCmiRT9hP5Pu'
    configFile: config/keys/ssh_config
    identityFile: config/keys/id_rsa
    forwardAgent: true
    multiplexing: true
    stage: production
    deploy_path: /var/www/test.lacuisine.de/private/
    typo3_webroot: ../../../web/
    branch: develop
    #// Project path
    application: tmp/

    #// Project repository
    repository: https://thomasruta@bitbucket.org/web-tp3/dev-rp.git
    git_tty: true
    keep_releases: 4

    #// Shared files/dirs between deploys
    shared_files: ['.env']
    shared_dirs: ['config']

    #// Writable dirs by web server
    writable_dirs: ['../tmp/','_temp', 'web','var']

tr:
    hostname: dev.thomasruta.de
    port: 22
    user: thomasruta_tudy
    public_key:  'config/keys/id_rsa.pub'
    private_key: 'config/keys/id_rsa'
    password:    'jpb0OIJlmCmiRT9hP5Pu'
    configFile: config/keys/ssh_config
    identityFile: config/keys/id_rsa
    forwardAgent: true
    multiplexing: true
    stage: staging
    deploy_path: /var/www/dev.thomasruta.de/private/
    typo3_webroot: ../../../web/
    branch: develop
    #// Project path
    application: tmp/

    #// Project repository
    repository: https://thomasruta@bitbucket.org/web-tp3/dev-rp.git
    git_tty: true
    keep_releases: 4

    #// Shared files/dirs between deploys
    shared_files: ['.env']
    shared_dirs: ['config']

    #// Writable dirs by web server
    writable_dirs: ['../tmp/','_temp', 'web','var']


cdu:
    hostname: old.r-p-it.com
    port: 22
    user: r_p_it_cdu
    public_key:  'config/keys/id_rsa.pub'
    private_key: 'config/keys/id_rsa'
    password:    'jpb0OIJlmCmiRT9hP5Pu'
    configFile: config/keys/ssh_config
    identityFile: config/keys/id_rsa
    forwardAgent: true
    multiplexing: true
    stage: production
    deploy_path: /var/www/old.r-p-it.com/private/
    typo3_webroot: ../../../web/
    branch: develop
    #// Project path
    application: tmp/

    #// Project repository
    repository: https://thomasruta@bitbucket.org/web-tp3/dev-rp.git
    git_tty: true
    keep_releases: 4

    #// Shared files/dirs between deploys
    shared_files: ['.env']
    shared_dirs: ['config']

    #// Writable dirs by web server
    writable_dirs: ['../tmp/','_temp', 'web','var']


tp3:
    hostname: dev.tp3.de
    port: 22
    user: thomasruta_tudy
    public_key:  'config/keys/id_rsa.pub'
    private_key: 'config/keys/id_rsa'
    password:    'jpb0OIJlmCmiRT9hP5Pu'
    configFile: config/keys/ssh_config
    identityFile: config/keys/id_rsa
    forwardAgent: true
    multiplexing: true
    stage: production
    deploy_path: /var/www/dev.tp3.de/private/
    typo3_webroot: ../../../web/
    branch: develop
    #// Project path
    application: tmp/

    #// Project repository
    repository: https://thomasruta@bitbucket.org/web-tp3/dev-rp.git
    git_tty: true
    keep_releases: 4

    #// Shared files/dirs between deploys
    shared_files: ['.env']
    shared_dirs: ['config']

    #// Writable dirs by web server
    writable_dirs: ['../tmp/','_temp', 'web','var']

rp:
    hostname: dev.r-p-it.com
    port: 22
    user: r_p_it_rp
    public_key:  'config/keys/id_rsa.pub'
    private_key: 'config/keys/id_rsa'
    password:    'jpb0OIJlmCmiRT9hP5Pu'
    configFile: config/keys/ssh_config
    identityFile: config/keys/id_rsa
    forwardAgent: true
    multiplexing: true
    stage: production
    deploy_path: /var/www/dev.r-p-it.com/private/
    typo3_webroot: ../web/
    branch: develop
    #// Project path
    application: tmp/

    #// Project repository
    repository: https://thomasruta@bitbucket.org/web-tp3/dev-rp.git
    git_tty: true
    keep_releases: 2

    #// Shared files/dirs between deploys
    shared_files: ['composer.json']
    shared_dirs: ['Build','config','bin']

    #// Writable dirs by web server
    writable_dirs: ['../tmp/','_temp']

srt:
    hostname: srt-wiesbaden.de
    port: 22
    user: srt_ssh
    public_key:  'config/keys/id_rsa.pub'
    private_key: 'config/keys/id_rsa'
    password:    'jpb0OIJlmCmiRT9hP5Pu'
    configFile: config/keys/ssh_config
    identityFile: config/keys/id_rsa
    forwardAgent: true
    multiplexing: true
    stage: production
    deploy_path: /var/www/srt-sanierung.de/private/
    typo3_webroot: ../web/
    branch: develop
    #// Project path
    application: tmp/

    #// Project repository
    repository: https://thomasruta@bitbucket.org/web-tp3/dev-rp.git
    git_tty: true
    keep_releases: 2

    #// Shared files/dirs between deploys
    shared_files: ['composer.json']
    shared_dirs: ['Build','config','bin']

    #// Writable dirs by web server
    writable_dirs: ['../tmp/','_temp']
