imports:
    - { resource: DefaultConfiguration, type: typo3, exclude: [LOG] }
    - { resource: 'includes/*.yaml', type: glob }
    - { resource: '../Packages/*/Configuration/Distribution/*.yaml', type: glob, ignore_errors: true }
    - { resource: local.settings.yaml }

BE:
    explicitADmode: explicitAllow
    loginSecurityLevel: rsa
DB:
    Connections:
        Default:
            charset: utf8
EXTCONF:
    helhum-typo3-console:
        initialUpgradeDone: '8.7'
    lang:
        availableLanguages:
            - cs
            - de
FE:
    addRootLineFields: 'subtitle,author,keywords,description,media,title,abstract,tsconfig,tp3microdata'
    loginSecurityLevel: rsa
    pageNotFoundOnCHashError: true
GFX:
    jpg_quality: '80'
    processor: GraphicsMagick
    processor_effects: -1
LOG:
    writerConfiguration:
        '%const(TYPO3\CMS\Core\Log\LogLevel::WARNING)%':
            TYPO3\CMS\Core\Log\Writer\FileWriter:
                logFile: '%env(TYPO3_PATH_COMPOSER_ROOT)%/var/log/typo3-warning.log'
SYS:
    caching:
        cacheConfigurations:
            extbase_object:
                backend: TYPO3\CMS\Core\Cache\Backend\ApcuBackend
    devIPmask: '80.151.59.179,1.1.1.128'
    displayErrors: false
    enableDeprecationLog: false
    reverseProxyIP: 2.2.2.2
    systemLogLevel: '2'
