services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Tp3\Tp3Businessview\:
    resource: '../Classes/*'

  Tp3\Tp3Businessview\Controller\ModuleController:
    public: true
