<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "tmpl"
 *
 * Auto generated by Extension Builder 2017-02-03
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'tmpl',
	'description' => 'Provider Extension for templating etc.',
	'category' => 'plugin',
	'author' => 'Connecta AG Dev Team',
	'author_email' => 'typo3@connecta.ag',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '0.4.1',
	'constraints' => array(
		'depends' => array(
			'typo3' => '7.6.0-8.7.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
            'cag_tests' => '*',
		),
	),
);
